### ISSUE TITLE
Policy update is ignored

### ISSUE THREAD

**Issue by laardee** [serverless-components/aws-iam-role#2]
If the policy, but not the service changes update is ignored.

As it is stated in the code comments 😁

[serverless.js L48](https://github.com/serverless-components/aws-iam-role/blob/master/serverless.js#L48) -> [utils.js L127](https://github.com/serverless-components/aws-iam-role/blob/master/utils.js#L127)

**Comment by eahefnawy** [comment]
oh yeah 🤦‍♂

**Comment by eahefnawy** [comment]
Fixed
