### ISSUE TITLE
Name not found in state (cloud branch)

### ISSUE THREAD

**Issue by serverlessguru** [serverless-components/aws-iam-role#7]
When trying to remove the AWS IAM role we are seeing an error pop up that the IAM role name is not found in state error:
https://github.com/serverless-components/aws-iam-role/blob/cloud/src/serverless.js#L96-L99

To replicate:
Create an AWS IAM Role component with a hardcoded name. Try to deploy then remove with `sls remove`.

Result:
AWS IAM Role is not removed, but says "done".

**Comment by eahefnawy** [comment]
Fixed.
