### ISSUE TITLE
Multiple Major Issues

### ISSUE THREAD

**Issue by austencollins** [serverless-components/aws-iam-role#8]
This component has multiple major issues:

* Custom policy support is not documented and there are no examples.

* `inputsChanged` does not accurately detect changes.  This component does not update.

* This Component uses ramda methods incorrectly, causing it to function inaccurately.  In particular, it uses `has` to check for properties, but it also incorrectly assumes those properties have values, which they don't.  For example, in `removeRolePolicy` and `addRolePolicy`.  All ramda methods should go away imo.  Plain javascript would make these issues obvious.

* When adding a custom policy, the user often runs into a "Malformed Policy" error from AWS IAM.  This is common because coding policies declaratively in YAML is error-prone.  However, if this error is thrown on first deployment, the Component then tries to update that policy on subsequent deployments.  Since it doesn't exist and the code does not check for its existence first, the Component is thrown into a perpetual error state and must be removed.

**Comment by eahefnawy** [comment]
Thanks, Austen. All of these issues are now fixed. I've also added integration test for the policy document use case. You can see the results of the tests here:

https://github.com/serverless-components/aws-iam-role/actions
